# Generated by Django 2.2.4 on 2019-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaign_send_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistentry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='online',
            field=models.BooleanField(blank=True, default=True, help_text='make a copy available online', verbose_name='available online'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sending Address'),
        ),
    ]
