# Generated by Django 2.2.17 on 2022-09-07 20:25

import campaign.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20190806_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlist',
            name='custom_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberlist',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='subscriberlist',
            name='filter_condition',
            field=campaign.fields.JSONField(blank=True, default='{}', help_text='Django ORM compatible lookup kwargs which are used to get the list of objects.', null=True),
        ),
    ]
