# Generated by Django 4.0.10 on 2023-08-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('campaign', '0008_auto_20220907_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Site'),
        ),
    ]
